# Generated by Django 5.2 on 2026-09-01 17:16

import portfolio.vlidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=998982312, max_length=12, validators=[portfolio.vlidators.validate_iranian_cellphone_number]),
            preserve_default=False,
        ),
    ]
